# Module Configuration File
#
# This file configures Hugo module settings, particularly module mounts which
# define how content is organized within the project.
#
# Mounts specify file paths in your project that Hugo should use when building
# the site. They allow for custom directory structures and integrating content
# from different locations.

## content
[[mounts]]
  disableWatch = false
  lang = ''
  source = 'content'
  target = 'content'

## data
[[mounts]]
  disableWatch = false
  lang = ''
  source = 'data'
  target = 'data'

## layouts
[[mounts]]
  source = "node_modules/@thulite/core/layouts"
  target = "layouts"

[[mounts]]
  disableWatch = false
  lang = ''
  source = 'layouts'
  target = 'layouts'

## i18n
[[mounts]]
  disableWatch = false
  lang = ''
  source = 'i18n'
  target = 'i18n'

## archetypes
[[mounts]]
  disableWatch = false
  lang = ''
  source = 'archetypes'
  target = 'archetypes'

## assets
[[mounts]]
  source = "node_modules/@thulite/core/assets"
  target = "assets"

[[mounts]]
  disableWatch = false
  lang = ''
  source = 'assets'
  target = 'assets'

## static
[[mounts]]
  disableWatch = false
  lang = ''
  source = 'static'
  target = 'static'
